"""
Django settings for middleware project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qe0jifq8xhc7-j(ehl%o_b*z)&d1*h3bwwo=n5co1=jxhre=vg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', "*"]

# CORS Configuration for SecureCipher Frontend Integration
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # SecureCipher crypto headers
    'x-secure-cipher',
    'x-signature',
    'x-request-id',
    'x-timestamp',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'api',  #Middleware Key Management API
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # CSRF middleware disabled for demo purposes
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow any user to access the API
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

ROOT_URLCONF = 'securecipher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'securecipher.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SecureCipher Logging Configuration


ROUTING_TABLE = {
    # Auth
    'auth_register': {'url': 'http://localhost:8001/api/auth/register/', 'method': 'POST'},
    'auth_login': {'url': 'http://localhost:8001/api/auth/login/', 'method': 'POST'},
    'auth_logout': {'url': 'http://localhost:8001/api/auth/logout/', 'method': 'POST'},
    'auth_set_pin': {'url': 'http://localhost:8001/api/auth/set_pin/', 'method': 'POST'},
    'auth_verify_pin': {'url': 'http://localhost:8001/api/auth/verify_pin/', 'method': 'POST'},

    # User Profile
    'user_get_profile': {'url': 'http://localhost:8001/api/user/profile/', 'method': 'GET'},
    'user_update_profile': {'url': 'http://localhost:8001/api/user/update_profile/', 'method': 'PUT'},

    # Bank Accounts
    'accounts_list': {'url': 'http://localhost:8001/api/accounts/', 'method': 'GET'},
    'accounts_get': {'url': 'http://localhost:8001/api/accounts/{account_id}/', 'method': 'GET'},
    'accounts_get_transactions': {'url': 'http://localhost:8001/api/accounts/{account_id}/transactions/', 'method': 'GET'},
    'accounts_get_balance': {'url': 'http://localhost:8001/api/accounts/{account_id}/balance/', 'method': 'GET'},

    # Transactions
    'transactions_list': {'url': 'http://localhost:8001/api/transactions/', 'method': 'GET'},
    'transactions_get': {'url': 'http://localhost:8001/api/transactions/{transaction_id}/', 'method': 'GET'},
    'transactions_transfer': {'url': 'http://localhost:8001/api/transactions/transfer/', 'method': 'POST'},

    # Beneficiaries
    'beneficiaries_list': {'url': 'http://localhost:8001/api/beneficiaries/', 'method': 'GET'},
    'beneficiaries_add': {'url': 'http://localhost:8001/api/beneficiaries/', 'method': 'POST'},
    'beneficiaries_get': {'url': 'http://localhost:8001/api/beneficiaries/{beneficiary_id}/', 'method': 'GET'},
    'beneficiaries_update': {'url': 'http://localhost:8001/api/beneficiaries/{beneficiary_id}/', 'method': 'PUT'},
    'beneficiaries_delete': {'url': 'http://localhost:8001/api/beneficiaries/{beneficiary_id}/', 'method': 'DELETE'},

    # Cards
    'cards_list': {'url': 'http://localhost:8001/api/cards/', 'method': 'GET'},
    'cards_add': {'url': 'http://localhost:8001/api/cards/', 'method': 'POST'},
    'cards_get': {'url': 'http://localhost:8001/api/cards/{card_id}/', 'method': 'GET'},
    'cards_update': {'url': 'http://localhost:8001/api/cards/{card_id}/', 'method': 'PUT'},
    'cards_delete': {'url': 'http://localhost:8001/api/cards/{card_id}/', 'method': 'DELETE'},
}